apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mmoda-backend.fullname" . }}
  labels:
    {{- include "mmoda-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mmoda-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mmoda-backend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.pvc.enabled }}
            - name: {{ include "mmoda-backend.fullname" . }}-pvc
              mountPath: {{ .Values.pvc.mountPath }}
          {{- end  }}
          {{- if .Values.ephemeralStorage.enabled }}
            - name: {{ include "mmoda-backend.fullname" . }}-ephemeral
              mountPath: {{ .Values.ephemeralStorage.mountPath }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.pvc.enabled }}
        - name: {{ include "mmoda-backend.fullname" . }}-pvc
          persistentVolumeClaim:
            claimName: {{ include "mmoda-backend.fullname" . }}-pvc
        {{- end }}
        {{- if .Values.ephemeralStorage.enabled }}
        - name: {{ include "mmoda-backend.fullname" . }}-ephemeral
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ {{ .Values.ephemeralStorage.accessMode }} ]
                resources:
                  requests:
                    storage: {{ .Values.ephemeralStorage.size }}
                storageClassName: {{ .Values.ephemeralStorage.storageClassName | default "" }}
        {{- end }}
        {{- with .Values.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
