apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mmodabot.rbacRoleName" . }}
  labels:
    {{- include "mmodabot.labels" . | nindent 4 }}
rules:
  # Permissions for k8s_interface.py
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"] # rw needed for helm to store releases
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete"]
  
  # Permissions for deployer.py (Helm CLI)
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mmodabot.rbacRoleName" . }}
  labels:
    {{- include "mmodabot.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mmodabot.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "mmodabot.rbacRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
